name: Secret Scanning

on:
  workflow_call:
    inputs:
      branches:
        description: 'Branches to monitor (default: main)'
        required: false
        type: string
        default: main
      runs_on:
        description: 'Type of runner (default: ubuntu-latest)'
        required: false
        type: string
        default: ubuntu-latest

jobs:
  test:
    runs-on: ${{ inputs.runs_on }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --results=verified,unknown
